const Image = {
    Section1: {
        Img1: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img2: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img3: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img4: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img5: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img6: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img7: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
    },
    Section2:{
        Img1: "https://drive.google.com/uc?id=1A6N2HwiU66aHYPcBOxkxASTuWn5BuPmW",
        Img2: "https://drive.google.com/uc?id=1A7YsKr8xhZAXKvQlCfWqAnqjJGsAzl9D",
        Img3: "https://drive.google.com/uc?id=19gtGD_bOoZpUfvU_7WMYLlntowxfTvFu",
        Img4: "https://drive.google.com/uc?id=1A3FsdFLsJHgkNCcbdZd3kwttymuHQt-E",
        Img5: "https://drive.google.com/uc?id=19oTERgSfVaMljAyt37ObYG9jVZ3BhE6l",
        Img6: "https://drive.google.com/uc?id=1A2o08y0QfGw849uCsaSqMP57T0VEbSms",
        Img7: "https://drive.google.com/uc?id=1A8UKbbHt4BF--gNQU03A_kMV0NouNTAl",
    },
    Section3: {
        Img1: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img2: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img3: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img4: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img5: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
    },
    Section4: "https://drive.google.com/uc?id=12zmq8aiALzMlEb1QrQuRmzNVXTMQZWc-",
    Section5: {
        Img1: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img2: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img3: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img4: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img5: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img6: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
    },
    Section6a: {
      Img1: "https://drive.google.com/uc?id=1N_ln_PzP5UiNeek84L6wLm7FrjIQ0FTj",
      Img2: "https://drive.google.com/uc?id=1WOtI0n-74ygfYEdSHnYh0P85qGtGgBP5",
      Img3: "https://drive.google.com/uc?id=10j0E88g-LtP9qxi4ClKZ8nsEPkCmK5xC",
    },
    Section6b: {
        Img1: "https://drive.google.com/uc?id=15fmR6UZFgUwWKoV3gN1XiswT_s5CCHhG",
        Img2: "https://drive.google.com/uc?id=15hL7ugXWad2AQf6ncYQUdps-7tGBzecD",
        Img3: "https://drive.google.com/uc?id=15hYD7t3c7_qQ9hmei2LsP2m1PAZLnGaI",
        Img4: "https://drive.google.com/uc?id=17hKPqSrQBtrk1LZkP1J9Y9Fc4o2ZS66V",
        Img5: "https://drive.google.com/uc?id=17ctjlslKuR_lvDqaueq_reLqzwbX006P",
        Img6: "https://drive.google.com/uc?id=17c1lkpgclYkerEO8ncz2PfLuuqJ0b25y",
        Img7: "https://drive.google.com/uc?id=17QIfnlFQVBx9ael5aG608PZuLATubodp",
        Img8: "https://drive.google.com/uc?id=1XcEkC5Z2ALy49W4G1nrhBPzJ6Hw7WuIm",
        Img9: "https://drive.google.com/uc?id=1MU0qbEsXUmrZBDpl9YekyHx73MF4_bdd",
        Img10: "https://drive.google.com/uc?id=1Ee6tW78ZuXDHxjgMrL0qNORZKiLdzMHF",
        Img11: "https://drive.google.com/uc?id=1SR6stsj_aFjMiUVoYxsUJqMbetObvAom",
      },
    Section7: {
        Img1: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img2: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img3: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img4: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img5: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img6: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
        Img7: "https://drive.google.com/uc?id=1Ixb8UTLWhOKjPdEEH7cibfwElh8Gs9Jm",
    },
  };
  
  export default Image;